### ISSUE TITLE
Add appropriate .md files to project

### ISSUE THREAD

**Issue by bobgott** [bobgott/hello-world#8]
**Is your feature request related to a problem? Please describe.**
Project does not have complete set of .md files

**Describe the solution you'd like**
Add: CHANGELOG, CONTRIBUTING, LICENSE and README to root. Add appropriate template files to templates folder

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
[reso-github-md-files.zip](https://github.com/bobgott/hello-world/files/2017843/reso-github-md-files.zip)

**Comment by voyinfo** [comment]
Working on this via pythonanywhere #8
